/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sz_log_types_pb.AwesomeMessage', null, global);
goog.exportSymbol('proto.sz_log_types_pb.SzExceptionType', null, global);
goog.exportSymbol('proto.sz_log_types_pb.SzServiceLog', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sz_log_types_pb.SzServiceLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sz_log_types_pb.SzServiceLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.sz_log_types_pb.SzServiceLog.displayName = 'proto.sz_log_types_pb.SzServiceLog';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.toObject = function(opt_includeInstance) {
  return proto.sz_log_types_pb.SzServiceLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sz_log_types_pb.SzServiceLog} msg The msg instance to transform.
 * @return {!Object}
 */
proto.sz_log_types_pb.SzServiceLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    szServiceName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    szMessage: jspb.Message.getFieldWithDefault(msg, 2, ""),
    szRequestId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    szException: (f = msg.getSzException()) && proto.sz_log_types_pb.SzExceptionType.toObject(includeInstance, f),
    szExtrasMap: (f = msg.getSzExtrasMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sz_log_types_pb.SzServiceLog}
 */
proto.sz_log_types_pb.SzServiceLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sz_log_types_pb.SzServiceLog;
  return proto.sz_log_types_pb.SzServiceLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sz_log_types_pb.SzServiceLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sz_log_types_pb.SzServiceLog}
 */
proto.sz_log_types_pb.SzServiceLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzServiceName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzMessage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzRequestId(value);
      break;
    case 5:
      var value = new proto.sz_log_types_pb.SzExceptionType;
      reader.readMessage(value,proto.sz_log_types_pb.SzExceptionType.deserializeBinaryFromReader);
      msg.setSzException(value);
      break;
    case 6:
      var value = msg.getSzExtrasMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sz_log_types_pb.SzServiceLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sz_log_types_pb.SzServiceLog} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.sz_log_types_pb.SzServiceLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSzServiceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSzMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSzRequestId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSzException();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.sz_log_types_pb.SzExceptionType.serializeBinaryToWriter
    );
  }
  f = message.getSzExtrasMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string sz_service_name = 1;
 * @return {string}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.getSzServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.sz_log_types_pb.SzServiceLog.prototype.setSzServiceName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string sz_message = 2;
 * @return {string}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.getSzMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.sz_log_types_pb.SzServiceLog.prototype.setSzMessage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string sz_request_id = 4;
 * @return {string}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.getSzRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.sz_log_types_pb.SzServiceLog.prototype.setSzRequestId = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional SzExceptionType sz_exception = 5;
 * @return {?proto.sz_log_types_pb.SzExceptionType}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.getSzException = function() {
  return /** @type{?proto.sz_log_types_pb.SzExceptionType} */ (
    jspb.Message.getWrapperField(this, proto.sz_log_types_pb.SzExceptionType, 5));
};


/** @param {?proto.sz_log_types_pb.SzExceptionType|undefined} value */
proto.sz_log_types_pb.SzServiceLog.prototype.setSzException = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.sz_log_types_pb.SzServiceLog.prototype.clearSzException = function() {
  this.setSzException(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.hasSzException = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * map<string, string> sz_extras = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.sz_log_types_pb.SzServiceLog.prototype.getSzExtrasMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


proto.sz_log_types_pb.SzServiceLog.prototype.clearSzExtrasMap = function() {
  this.getSzExtrasMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sz_log_types_pb.SzExceptionType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sz_log_types_pb.SzExceptionType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.sz_log_types_pb.SzExceptionType.displayName = 'proto.sz_log_types_pb.SzExceptionType';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sz_log_types_pb.SzExceptionType.prototype.toObject = function(opt_includeInstance) {
  return proto.sz_log_types_pb.SzExceptionType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sz_log_types_pb.SzExceptionType} msg The msg instance to transform.
 * @return {!Object}
 */
proto.sz_log_types_pb.SzExceptionType.toObject = function(includeInstance, msg) {
  var f, obj = {
    szExceptionMessage: jspb.Message.getFieldWithDefault(msg, 1, ""),
    szExceptionTrace: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sz_log_types_pb.SzExceptionType}
 */
proto.sz_log_types_pb.SzExceptionType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sz_log_types_pb.SzExceptionType;
  return proto.sz_log_types_pb.SzExceptionType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sz_log_types_pb.SzExceptionType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sz_log_types_pb.SzExceptionType}
 */
proto.sz_log_types_pb.SzExceptionType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzExceptionMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzExceptionTrace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sz_log_types_pb.SzExceptionType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sz_log_types_pb.SzExceptionType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sz_log_types_pb.SzExceptionType} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.sz_log_types_pb.SzExceptionType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSzExceptionMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSzExceptionTrace();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string sz_exception_message = 1;
 * @return {string}
 */
proto.sz_log_types_pb.SzExceptionType.prototype.getSzExceptionMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.sz_log_types_pb.SzExceptionType.prototype.setSzExceptionMessage = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string sz_exception_trace = 2;
 * @return {string}
 */
proto.sz_log_types_pb.SzExceptionType.prototype.getSzExceptionTrace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.sz_log_types_pb.SzExceptionType.prototype.setSzExceptionTrace = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sz_log_types_pb.AwesomeMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sz_log_types_pb.AwesomeMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.sz_log_types_pb.AwesomeMessage.displayName = 'proto.sz_log_types_pb.AwesomeMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sz_log_types_pb.AwesomeMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.sz_log_types_pb.AwesomeMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sz_log_types_pb.AwesomeMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.sz_log_types_pb.AwesomeMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    awesomeField: jspb.Message.getFieldWithDefault(msg, 1, ""),
    noAwesomeField: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sz_log_types_pb.AwesomeMessage}
 */
proto.sz_log_types_pb.AwesomeMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sz_log_types_pb.AwesomeMessage;
  return proto.sz_log_types_pb.AwesomeMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sz_log_types_pb.AwesomeMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sz_log_types_pb.AwesomeMessage}
 */
proto.sz_log_types_pb.AwesomeMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAwesomeField(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNoAwesomeField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sz_log_types_pb.AwesomeMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sz_log_types_pb.AwesomeMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sz_log_types_pb.AwesomeMessage} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.sz_log_types_pb.AwesomeMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAwesomeField();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNoAwesomeField();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string awesome_field = 1;
 * @return {string}
 */
proto.sz_log_types_pb.AwesomeMessage.prototype.getAwesomeField = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.sz_log_types_pb.AwesomeMessage.prototype.setAwesomeField = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string no_awesome_field = 2;
 * @return {string}
 */
proto.sz_log_types_pb.AwesomeMessage.prototype.getNoAwesomeField = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.sz_log_types_pb.AwesomeMessage.prototype.setNoAwesomeField = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.sz_log_types_pb);
